//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attractions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ReviewId { get; set; }
        public int UserId { get; set; }
        public int EntertainmentId { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime ReviewDate { get; set; }
    
        public virtual Entertainment Entertainment { get; set; }
        public virtual Users Users { get; set; }
    }
}
